name: preprocess_data

on:
  push:
    branches: [ main ]
    paths:
      - 'namadataset_raw/**'
      - 'preprocessing/**'
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List repository contents
      run: ls -R ${{ github.workspace }}

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install pandas numpy pyarrow

    - name: Run automate_Rakha.py
      run: |
        python preprocessing/automate_Rakha.py \
          --raw namadataset_raw/demand_history.csv \
          --outdir preprocessing/namadataset_preprocessing

    - name: Upload clean.parquet as artifact
      uses: actions/upload-artifact@v4
      with:
        name: clean_dataset
        path: preprocessing/namadataset_preprocessing/clean.parquet
